#___   __  __   ____    _____   ____    ___    ___       ____   __  __   ____    ____
#|_ _| |  \/  | |  _ \  | ____| |  _ \  |_ _|  / _ \     / ___| |  \/  | |  _ \  / ___|
#| |  | |\/| | | |_) | |  _|   | |_) |  | |  | | | |   | |     | |\/| | | | | | \___ \
#| |  | |  | | |  __/  | |___  |  _ <   | |  | |_| |   | |___  | |  | | | |_| |  ___) |
#|___| |_|  |_| |_|     |_____| |_| \_\ |___|  \___/     \____| |_|  |_| |____/  |____/
#
# Feito por: offluisera
# Versão: 0.1
#

#
# Defina a mensagem de título e subtitulo ao entrar no servidor
#

titulo-entrada: "&6&lIMPÉRIO SURVIVAL"
subtitulo-entrada: "&ftenha um bom jogo!"

#
# Defina a mensagem da troca do modo jogo
#

msg-criativo: "&aVocê alterou seu modo de jogo para criativo!"
msg-survival: "&aVocê alterou seu modo de jogo para sobrevivência!"
msg-spec: "&aVocê alterou seu modo de jogo para espectador!"
