name: ImperioCMDS
version: '1.0-SNAPSHOT'
main: luisera.imperiocmds.ImperioCMDS
api-version: 1.19
author: [offluisera]
description: Plugin para o servidor ImpérioSurvival
commands:
  gms:
    description: Entre no modo survial
    usage: /<command>
  gmc:
    description: Entre no modo criativo
    usage: /<command>
  gmspec:
    description: Entre no modo espectador
    usage: /<command>
  lixo:
    description: Abra uma lixeira
    usage: /<command>